// vue-apollo-client/src/App.vue
<script>
import { useQuery } from '@vue/apollo-composable'
import gql from 'graphql-tag'

export default {
    setup() {
        const { result, loading, error } = useQuery(gql`
      query getGenes {
        genes {
          identifier
          name
          description
        }
      }
    `)

        return {
            result,
            loading,
            error,
        }
    },
}
</script>

<template>
  <h1>Here be some genes (Vue.js)</h1>
  <div v-if="loading">Loading...</div>
  <div v-else-if="error">Error: {{ error.message }}</div>
  <ul v-if="result && result.genes">
    <li v-for="gene of result.genes" :key="gene.identifier">
      <b>{{ gene.name }}</b>
      <br/>
      {{ gene.description }}
    </li>
  </ul>
</template>

<style>
#app {
    font-family: Avenir, Helvetica, Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
</style>

// react-apollo-client/src/App.jsx
import { useQuery, gql } from '@apollo/client';
import './App.css';

function App() {
    const { data, loading, error } = useQuery(gql`
      query getGenes {
        genes {
          identifier
          name
          description
        }
      }
    `);
    if (loading) return (
        <div>Loading data...</div>
    );
    if (error) return (
        <div>Error: {error.message}</div>
    );
    return (
        <div className="App">
            <h1>Here be some genes (React)</h1>
            <ul>
                {data.genes.map(gene => (
                    <li key={gene.identifier}>
                        <b>{ gene.name }</b>
                        <br/>
                        { gene.description }
                    </li>
                ))}
            </ul>
        </div>
    );
}

export default App;
